apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: radarr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      automountServiceAccountToken: true
      containers:
        - envFrom:
            - configMapRef:
                name: common-vars
                optional: false
          image: lscr.io/linuxserver/radarr:4.1.0@sha256:57794fbfdb2cc8e4ee5ad9f12f0f3fe79b5feec0e7794275778f4c9f5c2d9ccd
          imagePullPolicy: IfNotPresent
          env:
            - name: "DOCKER_MODS"
              value: "linuxserver/mods:universal-stdout-logs"
            - name: LOGS_TO_STDOUT
              value: "/config/logs/radarr.txt"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - SETGID
                - SETUID
                #- NET_RAW
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 7878
            timeoutSeconds: 1
          name: radarr
          ports:
            - containerPort: 7878
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 7878
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "4"
              memory: 1G
            requests:
              cpu: 500m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              mountPropagation: None
              name: config
            - mountPath: /media
              mountPropagation: None
              name: media
            - mountPath: /torrents
              mountPropagation: None
              name: torrents
            - mountPath: /etc/localtime
              mountPropagation: None
              name: timezone
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeSelector:
        kubernetes.io/hostname: debian-storage
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: File
          name: timezone
        - hostPath:
            path: /media
            type: Directory
          name: media
        - hostPath:
            path: /media/Torrents
            type: Directory
          name: torrents
        - hostPath:
            path: /work/storage/configs/radarr
            type: Directory
          name: config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 7878
      protocol: TCP
      targetPort: 7878
  selector:
    app: radarr
  sessionAffinity: None
  type: ClusterIP
