apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: remote-apps
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.7.0
    helm:
      releaseName: kube-state-metrics
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
    