---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: paperless
    namespace: argocd
spec:
    project: remote-apps
    source:
        chart: paperless
        repoURL: https://k8s-at-home.com/charts/
        targetRevision: 9.0.0
        helm:
            releaseName: paperless
            values: |
                podAnnotations:
                    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
                    vault.security.banzaicloud.io/vault-env-from-path: secret/data/deploy/paperless
                controller:
                    replicas: 1
                env:
                    PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_X_AUTH_REQUEST_PREFERRED_USERNAME
                    PAPERLESS_ENABLE_HTTP_REMOTE_USER: true
                    PAPERLESS_REDIS: redis://redis:6379
                    PAPERLESS_PORT: 8000
                    PAPERLESS_TIME_ZONE: America/Los_Angeles
                    USERMAP_GID: 997
                    USERMAP_UID: 998
                ingress:
                    main:
                        enabled: false
                persistence:
                    config:
                        enabled: true
                        hostPath: /cache/configs/paperless/config
                        hostPathType: Directory
                        type: hostPath
                    consume:
                        enabled: true
                        hostPath: /cache/configs/paperless/consume
                        hostPathType: Directory
                        type: hostPath
                    data:
                        enabled: true
                        hostPath: /cache/configs/paperless/data
                        hostPathType: Directory
                        size: 20Gi
                        type: hostPath
                    media:
                        enabled: true
                        hostPath: /cache/configs/paperless/media
                        hostPathType: Directory
                        size: 20Gi
                        type: hostPath
                resources:
                    limits:
                        cpu: 16
                        memory: 4G
                    requests:
                        cpu: 2
                        memory: 4G
    destination:
        server: https://kubernetes.default.svc
        namespace: default
