apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
spec:
  project: remote-apps
  source:
    chart: vault
    repoURL: https://emberstack.github.io/helm-charts
    targetRevision: 6.1.47
    helm:
      releaseName: reflector
      values: |
         image:
           tag: 6.1.47@sha256:a0a5c4020f6d2771893f83111d9fc09425cc874d6626208069caf8dcba179e10
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
    