---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: vaultwarden
    namespace: argocd
spec:
    project: remote-apps
    source:
        chart: vaultwarden
        repoURL: https://k8s-at-home.com/charts
        targetRevision: 5.0.0
        helm:
            releaseName: vaultwarden
            values: |
                image:
                  tag: 1.25.1-alpine@sha256:d75a3780af0455f7af3f34369cf814e55d69c5d258f02ac3c080e5805b9f4eec
                podAnnotations:
                    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
                env:
                  DATA_FOLDER: /work/storage/configs/vaultwarden
                  DOMAIN: vault:secret/data/deploy/domain#vaultwarden_domain
                  GROUPID: 997
                  SIGNUPS_ALLOWED: false
                  TZ: America/Los_Angeles
                  USERID: 998
                persistence:
                  config:
                    enabled: true
                    hostPath: /work/storage/configs/vaultwarden
                    type: hostPath
                resources:
                  limits:
                    cpu: 4
                    memory: 100Mi
                  requests:
                    cpu: 50m
                    memory: 30Mi
    destination:
        server: https://kubernetes.default.svc
        namespace: default
